language: node_js
node_js:
  - "8.10"
cache:
  directories:
    - "node_modules"
install:
- npm install -g codecov
- npm install --save-dev nyc
script:
  - npm run checks
  - codecov
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then ./scripts/test_integration.sh ; fi # a pull request

deploy:
  provider: script
  skip_cleanup: true
  script: npm run semantic-release
  on:
    branch: master
after_success:
  - bash <(curl -s https://codecov.io/bash)